package envelope_test

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/everstrat-xyz/keepers/pkg/envelope"
)

// fixture mirrors one entry of testdata/fixtures.json, generated by
// scripts/gen-envelope-fixtures.sh via `cast abi-encode`. The golden bytes come
// from Foundry's Solidity encoder, so these tests compare Go against the actual
// other side of the ABI boundary rather than against themselves.
type fixture struct {
	Name          string `json:"name"`
	Note          string `json:"note"`
	ChainSelector string `json:"chainSelector"`
	Sequence      string `json:"sequence"`
	ObservedAt    string `json:"observedAt"`
	Action        uint8  `json:"action"`
	Params        string `json:"params"`
	Report        string `json:"report"`
}

func (f fixture) envelope(t *testing.T) envelope.Envelope {
	t.Helper()
	return envelope.Envelope{
		ChainSelector: mustUint64(t, f.ChainSelector),
		Sequence:      mustUint64(t, f.Sequence),
		ObservedAt:    mustUint64(t, f.ObservedAt),
		Action:        f.Action,
		Params:        mustHex(t, f.Params),
	}
}

func mustUint64(t *testing.T, s string) uint64 {
	t.Helper()
	v, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		t.Fatalf("parsing %q: %v", s, err)
	}
	return v
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
	if err != nil {
		t.Fatalf("decoding %q: %v", s, err)
	}
	return b
}

func loadFixtures(t *testing.T) []fixture {
	t.Helper()
	raw, err := os.ReadFile("testdata/fixtures.json")
	if err != nil {
		t.Fatalf("reading fixtures: %v", err)
	}
	var out []fixture
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatalf("parsing fixtures: %v", err)
	}
	if len(out) == 0 {
		t.Fatal("fixtures file is empty")
	}
	return out
}

// TestEncodeMatchesSolidityFixtures is the parity test the issue's acceptance
// criteria turn on: Go must produce the exact bytes Solidity's
// abi.encode(Envelope) produces, or CREReceiverBase.onReport reverts on decode.
func TestEncodeMatchesSolidityFixtures(t *testing.T) {
	for _, f := range loadFixtures(t) {
		t.Run(f.Name, func(t *testing.T) {
			got, err := f.envelope(t).Encode()
			if err != nil {
				t.Fatalf("Encode() error = %v", err)
			}
			want := strings.ToLower(strings.TrimPrefix(f.Report, "0x"))
			if hex.EncodeToString(got) != want {
				t.Errorf("Encode() mismatch for %s (%s)\n got: 0x%s\nwant: %s",
					f.Name, f.Note, hex.EncodeToString(got), f.Report)
			}
		})
	}
}

func TestDecodeFixtures(t *testing.T) {
	for _, f := range loadFixtures(t) {
		t.Run(f.Name, func(t *testing.T) {
			want := f.envelope(t)
			got, err := envelope.Decode(mustHex(t, f.Report))
			if err != nil {
				t.Fatalf("Decode() error = %v", err)
			}
			if got.ChainSelector != want.ChainSelector {
				t.Errorf("ChainSelector = %d, want %d", got.ChainSelector, want.ChainSelector)
			}
			if got.Sequence != want.Sequence {
				t.Errorf("Sequence = %d, want %d", got.Sequence, want.Sequence)
			}
			if got.ObservedAt != want.ObservedAt {
				t.Errorf("ObservedAt = %d, want %d", got.ObservedAt, want.ObservedAt)
			}
			if got.Action != want.Action {
				t.Errorf("Action = %d, want %d", got.Action, want.Action)
			}
			if hex.EncodeToString(got.Params) != hex.EncodeToString(want.Params) {
				t.Errorf("Params = 0x%x, want 0x%x", got.Params, want.Params)
			}
		})
	}
}

func TestEncodeDecodeRoundTrip(t *testing.T) {
	for _, f := range loadFixtures(t) {
		t.Run(f.Name, func(t *testing.T) {
			original := f.envelope(t)
			encoded, err := original.Encode()
			if err != nil {
				t.Fatalf("Encode() error = %v", err)
			}
			decoded, err := envelope.Decode(encoded)
			if err != nil {
				t.Fatalf("Decode() error = %v", err)
			}
			reencoded, err := decoded.Encode()
			if err != nil {
				t.Fatalf("re-Encode() error = %v", err)
			}
			if hex.EncodeToString(encoded) != hex.EncodeToString(reencoded) {
				t.Errorf("round trip is not stable\nfirst:  0x%x\nsecond: 0x%x", encoded, reencoded)
			}
		})
	}
}

func TestEncodeRejectsZeroHeaderFields(t *testing.T) {
	base := envelope.Envelope{ChainSelector: 16015286601757825753, Sequence: 1, ObservedAt: 1700000000}

	tests := []struct {
		name string
		mut  func(e *envelope.Envelope)
		want error
	}{
		{"zero chain selector", func(e *envelope.Envelope) { e.ChainSelector = 0 }, envelope.ErrZeroChainSelector},
		{"zero sequence", func(e *envelope.Envelope) { e.Sequence = 0 }, envelope.ErrZeroSequence},
		{"zero observedAt", func(e *envelope.Envelope) { e.ObservedAt = 0 }, envelope.ErrZeroObservedAt},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			e := base
			tt.mut(&e)
			if _, err := e.Encode(); !errors.Is(err, tt.want) {
				t.Errorf("Encode() error = %v, want %v", err, tt.want)
			}
		})
	}
}

func TestDecodeRejectsGarbage(t *testing.T) {
	tests := []struct {
		name   string
		report []byte
	}{
		{"empty", nil},
		{"truncated header", make([]byte, 31)},
		{"offset word only", make([]byte, 32)},
		{"offset points past the end", func() []byte {
			b := make([]byte, 64)
			b[31] = 0xff // tuple offset = 255, beyond the buffer
			return b
		}()},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := envelope.Decode(tt.report); err == nil {
				t.Error("Decode() succeeded on malformed input, want error")
			}
		})
	}
}

func TestValidate(t *testing.T) {
	const (
		sel = uint64(16015286601757825753)
		age = uint64(3600)
	)
	now := time.Unix(1700003600, 0)
	state := envelope.ReceiverState{ChainSelector: sel, LastSequence: 10, MaxReportAge: age}

	tests := []struct {
		name string
		e    envelope.Envelope
		want error
	}{
		{
			name: "fresh report just inside the age window",
			e:    envelope.Envelope{ChainSelector: sel, Sequence: 11, ObservedAt: 1700000000},
		},
		{
			name: "observedAt equal to now",
			e:    envelope.Envelope{ChainSelector: sel, Sequence: 11, ObservedAt: uint64(now.Unix())},
		},
		{
			name: "wrong chain",
			e:    envelope.Envelope{ChainSelector: 5009297550715157269, Sequence: 11, ObservedAt: 1700000000},
			want: envelope.ErrWrongChain,
		},
		{
			name: "sequence equal to lastSequence",
			e:    envelope.Envelope{ChainSelector: sel, Sequence: 10, ObservedAt: 1700000000},
			want: envelope.ErrReplayedSequence,
		},
		{
			name: "sequence below lastSequence",
			e:    envelope.Envelope{ChainSelector: sel, Sequence: 9, ObservedAt: 1700000000},
			want: envelope.ErrReplayedSequence,
		},
		{
			name: "observedAt in the future",
			e:    envelope.Envelope{ChainSelector: sel, Sequence: 11, ObservedAt: uint64(now.Unix()) + 1},
			want: envelope.ErrObservedInFuture,
		},
		{
			name: "one second past MAX_REPORT_AGE",
			e:    envelope.Envelope{ChainSelector: sel, Sequence: 11, ObservedAt: 1700000000 - 1},
			want: envelope.ErrStaleReport,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.e.Validate(state, now)
			switch {
			case tt.want == nil && err != nil:
				t.Errorf("Validate() error = %v, want nil", err)
			case tt.want != nil && !errors.Is(err, tt.want):
				t.Errorf("Validate() error = %v, want %v", err, tt.want)
			}
		})
	}
}

func TestNextSequence(t *testing.T) {
	got, err := envelope.NextSequence(0)
	if err != nil || got != 1 {
		t.Errorf("NextSequence(0) = %d, %v; want 1, nil", got, err)
	}
	got, err = envelope.NextSequence(41)
	if err != nil || got != 42 {
		t.Errorf("NextSequence(41) = %d, %v; want 42, nil", got, err)
	}
	if _, err := envelope.NextSequence(^uint64(0)); err == nil {
		t.Error("NextSequence(uint64 max) succeeded, want error")
	}
}

// TestNextSequenceAcceptedByValidate ties the two halves together: a report
// numbered from a freshly-read lastSequence must survive Validate against that
// same state.
func TestNextSequenceAcceptedByValidate(t *testing.T) {
	const sel = uint64(16015286601757825753)
	now := time.Unix(1700000000, 0)
	state := envelope.ReceiverState{ChainSelector: sel, LastSequence: 7, MaxReportAge: 3600}

	seq, err := envelope.NextSequence(state.LastSequence)
	if err != nil {
		t.Fatalf("NextSequence() error = %v", err)
	}
	e := envelope.Envelope{ChainSelector: sel, Sequence: seq, ObservedAt: uint64(now.Unix())}
	if err := e.Validate(state, now); err != nil {
		t.Errorf("Validate() error = %v, want nil", err)
	}
}

func TestDeadlineAndRemainingBudget(t *testing.T) {
	observed := time.Unix(1700000000, 0)
	const age = uint64(3600)

	if got, want := envelope.Deadline(observed, age), time.Unix(1700003600, 0); !got.Equal(want) {
		t.Errorf("Deadline() = %v, want %v", got, want)
	}
	if got, want := envelope.RemainingBudget(observed, age, observed), time.Hour; got != want {
		t.Errorf("RemainingBudget() at observation = %v, want %v", got, want)
	}
	if got := envelope.RemainingBudget(observed, age, observed.Add(2*time.Hour)); got >= 0 {
		t.Errorf("RemainingBudget() past deadline = %v, want negative", got)
	}
}

func TestCanPlausiblyDeliver(t *testing.T) {
	observed := time.Unix(1700000000, 0)
	const age = uint64(3600) // 1h

	tests := []struct {
		name string
		now  time.Time
		want bool
	}{
		{"fresh report", observed, true},
		{"just outside the margin", observed.Add(time.Hour - envelope.DeliveryMargin - time.Second), true},
		{"at exactly the margin", observed.Add(time.Hour - envelope.DeliveryMargin), false},
		{"inside the margin", observed.Add(time.Hour - envelope.DeliveryMargin + time.Second), false},
		{"past the deadline", observed.Add(2 * time.Hour), false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := envelope.CanPlausiblyDeliver(observed, age, tt.now); got != tt.want {
				t.Errorf("CanPlausiblyDeliver(now=%s) = %v, want %v", tt.now.Format(time.Kitchen), got, tt.want)
			}
		})
	}
}

// TestCanPlausiblyDeliverAgreesWithValidate pins the relationship the W1/W2
// pre-flight relies on: everything Validate accepts must also be plausibly
// deliverable, except the band inside DeliveryMargin of the deadline, where
// the margin check is the stricter gate. The reverse must never hold — a
// report past its deadline can pass no check at all.
func TestCanPlausiblyDeliverAgreesWithValidate(t *testing.T) {
	const (
		sel = uint64(16015286601757825753)
		age = uint64(3600)
	)
	observed := time.Unix(1700000000, 0)
	e := envelope.Envelope{ChainSelector: sel, Sequence: 2, ObservedAt: uint64(observed.Unix())}
	state := envelope.ReceiverState{ChainSelector: sel, LastSequence: 1, MaxReportAge: age}

	// Validate accepts anything up to and including the deadline; the margin
	// carves out the last DeliveryMargin of it.
	acceptedByValidate := observed.Add(time.Duration(age)*time.Second - time.Second)
	if err := e.Validate(state, acceptedByValidate); err != nil {
		t.Fatalf("Validate() at deadline-1s = %v, want nil", err)
	}
	if envelope.CanPlausiblyDeliver(observed, age, acceptedByValidate) {
		t.Error("CanPlausiblyDeliver is true at deadline-1s; the margin must be stricter than Validate here")
	}
	if err := e.Validate(state, observed.Add(time.Duration(age)*time.Second+time.Second)); err == nil {
		t.Error("Validate() past the deadline succeeded, want ErrStaleReport")
	}
}

// TestPrepareKeepsBytesAndEnvelopeInStep covers the pairing both keepers
// validate through: the Envelope handed to Validate must be what actually
// decodes out of the bytes handed to writeReport, not a parallel struct that
// could drift from them.
func TestPrepareKeepsBytesAndEnvelopeInStep(t *testing.T) {
	original := envelope.Envelope{
		ChainSelector: 16015286601757825753,
		Sequence:      7,
		ObservedAt:    1_700_000_000,
		Action:        2,
		Params:        []byte{0x01, 0x02},
	}
	encoded, err := original.Encode()
	if err != nil {
		t.Fatal(err)
	}

	prepared, err := envelope.Prepare(encoded)
	if err != nil {
		t.Fatal(err)
	}

	if string(prepared.Encoded) != string(encoded) {
		t.Error("Prepare changed the encoded bytes; the report written must be the bytes validated")
	}
	if prepared.Envelope.ChainSelector != original.ChainSelector ||
		prepared.Envelope.Sequence != original.Sequence ||
		prepared.Envelope.ObservedAt != original.ObservedAt ||
		prepared.Envelope.Action != original.Action {
		t.Errorf("Prepare decoded %+v, want %+v", prepared.Envelope, original)
	}
}

func TestPrepareRejectsUndecodableBytes(t *testing.T) {
	if _, err := envelope.Prepare([]byte{0x01, 0x02, 0x03}); err == nil {
		t.Error("Prepare(garbage) = nil error, want a decode error")
	}
}
